import type { MetadataRoute } from "next";
import { articles } from "@/content/blog";
import { SERVICE_PAGES, INDUSTRY_PAGES, PRICE_PAGES } from "@/data/keywords";
import { BLOG_POSTS } from "@/data/blog-posts";
import { getAllGeoSlugs } from "@/data/geo-pages";

const BASE_URL = "https://www.lx3.ai";

// EN slug mappings for services that have explicit routing translations
const SERVICE_EN_SLUGS: Record<string, string> = {
  "desarrollo-web": "web-development",
  "crm-personalizado": "custom-crm",
  "tienda-online": "online-store",
  "posicionamiento-web": "seo",
  "landing-pages": "landing-pages",
  "sistema-cotizaciones": "quoting-system",
  "desarrollo-fullstack": "fullstack-development",
  "ecommerce-medida": "custom-ecommerce",
  "aplicaciones-internas": "internal-apps",
  "automatizacion-ia": "ai-automation",
  "sitios-web": "websites",
  "consultoria": "consulting",
};

const GEO_EN_PREFIXES: Record<string, string> = {
  "desarrollo-web": "web-development",
  "software-a-medida": "custom-software",
  "crm-personalizado": "custom-crm",
};

function langAlts(es: string, en: string) {
  return {
    languages: {
      es: `${BASE_URL}${es}`,
      en: `${BASE_URL}${en}`,
      "x-default": `${BASE_URL}${es}`,
    },
  };
}

// Only truly unique pages that are NOT generated by dynamic routes below
const staticRoutes: { es: string; en: string; priority?: number }[] = [
  { es: "/es", en: "/en" },
  { es: "/es/servicios", en: "/en/services" },
  { es: "/es/casos", en: "/en/cases" },
  { es: "/es/casos/opai-gard-security", en: "/en/cases/opai-gard-security" },
  { es: "/es/casos/gard-sitio-web", en: "/en/cases/gard-website" },
  { es: "/es/casos/casa-orfebre", en: "/en/cases/casa-orfebre" },
  { es: "/es/blog", en: "/en/blog" },
  { es: "/es/sobre-nosotros", en: "/en/about-us" },
  { es: "/es/contacto", en: "/en/contact" },
  // Static service pages that are NOT in SERVICE_PAGES (no dynamic overlap)
  { es: "/es/servicios/aplicaciones-internas", en: "/en/services/internal-apps", priority: 0.8 },
  { es: "/es/servicios/sitios-web", en: "/en/services/websites", priority: 0.8 },
  { es: "/es/servicios/consultoria", en: "/en/services/consulting", priority: 0.8 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  // ── Static pages ──────────────────────────────────────────────────────────
  const staticPages: MetadataRoute.Sitemap = staticRoutes.map(({ es, en, priority: p }) => ({
    url: `${BASE_URL}${es}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: p ?? (es === "/es" ? 1 : 0.7),
    alternates: langAlts(es, en),
  }));

  // ── Blog posts (editorial) ────────────────────────────────────────────────
  const blogPosts: MetadataRoute.Sitemap = articles.map((article) => ({
    url: `${BASE_URL}/es/blog/${article.slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.6,
    alternates: langAlts(`/es/blog/${article.slug}`, `/en/blog/${article.slug}`),
  }));

  // ── SEO programmatic service pages (/servicios/[slug]) ────────────────────
  const serviceRoutes: MetadataRoute.Sitemap = SERVICE_PAGES.map((s) => {
    const enSlug = SERVICE_EN_SLUGS[s.slug] ?? s.slug;
    return {
      url: `${BASE_URL}/es/servicios/${s.slug}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.9,
      alternates: langAlts(`/es/servicios/${s.slug}`, `/en/services/${enSlug}`),
    };
  });

  // ── SEO industry / solution pages (/soluciones/[slug]) ────────────────────
  const industryRoutes: MetadataRoute.Sitemap = INDUSTRY_PAGES.map((i) => ({
    url: `${BASE_URL}/es/soluciones/${i.slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.8,
    alternates: langAlts(`/es/soluciones/${i.slug}`, `/en/solutions/${i.slug}`),
  }));

  // ── SEO price pages (/precio/[slug]) ──────────────────────────────────────
  const priceRoutes: MetadataRoute.Sitemap = PRICE_PAGES.map((p) => ({
    url: `${BASE_URL}/es/precio/${p.slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.85,
    alternates: langAlts(`/es/precio/${p.slug}`, `/en/pricing/${p.slug}`),
  }));

  // ── Geo service pages (from geo-pages data — single source of truth) ──────
  const geoServiceTypes = ["desarrollo-web", "software-a-medida", "crm-personalizado"] as const;
  const geoRoutes: MetadataRoute.Sitemap = geoServiceTypes.flatMap((serviceType) => {
    const enPrefix = GEO_EN_PREFIXES[serviceType] ?? serviceType;
    return getAllGeoSlugs(serviceType).map((citySlug) => ({
      url: `${BASE_URL}/es/${serviceType}/${citySlug}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.75,
      alternates: langAlts(
        `/es/${serviceType}/${citySlug}`,
        `/en/${enPrefix}/${citySlug}`
      ),
    }));
  });

  // ── SEO programmatic blog posts (/seo-blog/[slug]) ────────────────────────
  const seoBlogRoutes: MetadataRoute.Sitemap = BLOG_POSTS.map((p) => ({
    url: `${BASE_URL}/es/seo-blog/${p.slug}`,
    lastModified: new Date(p.updatedAt),
    changeFrequency: "monthly" as const,
    priority: 0.7,
    alternates: langAlts(`/es/seo-blog/${p.slug}`, `/en/seo-blog/${p.slug}`),
  }));

  return [
    ...staticPages,
    ...blogPosts,
    ...serviceRoutes,
    ...industryRoutes,
    ...priceRoutes,
    ...geoRoutes,
    ...seoBlogRoutes,
  ];
}
