import type { MetadataRoute } from "next";
import { articles } from "@/content/blog";
import { SERVICE_PAGES, INDUSTRY_PAGES } from "@/data/keywords";
import { BLOG_POSTS } from "@/data/blog-posts";
import { SERVICE_EN_SLUGS } from "@/lib/seo";

const BASE_URL = "https://www.lx3.ai";

function langAlts(es: string, en: string) {
  return {
    languages: {
      es: `${BASE_URL}${es}`,
      en: `${BASE_URL}${en}`,
      "x-default": `${BASE_URL}${es}`,
    },
  };
}

// Only truly unique pages that are NOT generated by dynamic routes below
const staticRoutes: { es: string; en: string; priority?: number }[] = [
  { es: "/es", en: "/en" },
  { es: "/es/servicios", en: "/en/services" },
  { es: "/es/casos", en: "/en/cases" },
  { es: "/es/casos/opai-gard-security", en: "/en/cases/opai-gard-security" },
  { es: "/es/casos/gard-sitio-web", en: "/en/cases/gard-website" },
  { es: "/es/casos/casa-orfebre", en: "/en/cases/casa-orfebre" },
  { es: "/es/blog", en: "/en/blog" },
  { es: "/es/sobre-nosotros", en: "/en/about-us" },
  { es: "/es/contacto", en: "/en/contact" },
  // Static service pages that are NOT in SERVICE_PAGES (no dynamic overlap)
  { es: "/es/servicios/aplicaciones-internas", en: "/en/services/internal-apps", priority: 0.8 },
  { es: "/es/servicios/sitios-web", en: "/en/services/websites", priority: 0.8 },
  { es: "/es/servicios/consultoria", en: "/en/services/consulting", priority: 0.8 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  // ── Static pages ──────────────────────────────────────────────────────────
  const staticPages: MetadataRoute.Sitemap = staticRoutes.map(({ es, en, priority: p }) => ({
    url: `${BASE_URL}${es}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: p ?? (es === "/es" ? 1 : 0.7),
    alternates: langAlts(es, en),
  }));

  // ── Blog posts (editorial) ────────────────────────────────────────────────
  const blogPosts: MetadataRoute.Sitemap = articles.map((article) => ({
    url: `${BASE_URL}/es/blog/${article.slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.6,
    alternates: langAlts(`/es/blog/${article.slug}`, `/en/blog/${article.slug}`),
  }));

  // ── SEO programmatic service pages (/servicios/[slug]) ────────────────────
  const serviceRoutes: MetadataRoute.Sitemap = SERVICE_PAGES.map((s) => {
    const enSlug = SERVICE_EN_SLUGS[s.slug] ?? s.slug;
    return {
      url: `${BASE_URL}/es/servicios/${s.slug}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.9,
      alternates: langAlts(`/es/servicios/${s.slug}`, `/en/services/${enSlug}`),
    };
  });

  // ── SEO industry / solution pages (/soluciones/[slug]) ────────────────────
  const industryRoutes: MetadataRoute.Sitemap = INDUSTRY_PAGES.map((i) => ({
    url: `${BASE_URL}/es/soluciones/${i.slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.8,
    alternates: langAlts(`/es/soluciones/${i.slug}`, `/en/solutions/${i.slug}`),
  }));

  // ── SEO programmatic blog posts (/seo-blog/[slug]) ────────────────────────
  const seoBlogRoutes: MetadataRoute.Sitemap = BLOG_POSTS.map((p) => ({
    url: `${BASE_URL}/es/seo-blog/${p.slug}`,
    lastModified: new Date(p.updatedAt),
    changeFrequency: "monthly" as const,
    priority: 0.7,
    alternates: langAlts(`/es/seo-blog/${p.slug}`, `/en/seo-blog/${p.slug}`),
  }));

  return [
    ...staticPages,
    ...blogPosts,
    ...serviceRoutes,
    ...industryRoutes,
    ...seoBlogRoutes,
  ];
}
